name: Parkour
main: parkour\ParkourMain
version: 1.0.0
api: ["4.5.1"]
author: "vP3aZy"
website: "https://github.com/vP3aZy"

permissions:
  parkour.cmd.create:
    default: OP
  parkour.cmd.join:
    default: true
  parkour.cmd.list:
    default: OP
  parkour.cmd.delete:
    default: OP
  parkour.cmd.checkpoint:
    default: OP